import type { Metadata } from "next";
import "@gaffaai/uikit/src/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased md:min-h-screen px-4 `}>{children}</body>
    </html>
  );
}
